export const agendas = [
  {
    id: 1,
    date: {
      start: "2024-08-01T18:50:15.000Z",
      end: "2024-08-01T19:50:15.000Z",
    },
    location: "Online",
    title: "Meeting with Team A",
    invites: [
      "alice.smith@example.com",
      "bob.jones@example.com",
      "carol.taylor@example.com",
    ],
  },
  {
    id: 2,
    date: {
      start: "2024-08-02T09:00:00.000Z",
      end: "2024-08-02T10:00:00.000Z",
    },
    location: "Rua Teste, 123",
    title: "Project Kickoff",
    invites: [
      "dave.lee@example.com",
      "eva.williams@example.com",
      "frank.brown@example.com",
    ],
  },
  {
    id: 3,
    date: {
      start: "2024-08-03T14:30:00.000Z",
      end: "2024-08-03T15:30:00.000Z",
    },
    location: "Online",
    title: "Design Review",
    invites: [
      "george.clark@example.com",
      "hannah.martin@example.com",
      "ian.davis@example.com",
    ],
  },
  {
    id: 4,
    date: {
      start: "2024-08-04T11:00:00.000Z",
      end: "2024-08-04T12:00:00.000Z",
    },
    location: "Office, Room 301",
    title: "Strategy Meeting",
    invites: [
      "julia.moore@example.com",
      "kyle.jackson@example.com",
      "lisa.miller@example.com",
    ],
  },
  {
    id: 5,
    date: {
      start: "2024-07-10T10:00:00.000Z",
      end: "2024-07-10T11:00:00.000Z",
    },
    location: "Conference Room A",
    title: "Budget Planning",
    invites: [
      "michael.wilson@example.com",
      "nancy.hernandez@example.com",
      "oscar.hill@example.com",
    ],
  },
  {
    id: 6,
    date: {
      start: "2024-07-15T15:00:00.000Z",
      end: "2024-07-15T16:30:00.000Z",
    },
    location: "Online",
    title: "Marketing Strategy",
    invites: [
      "patricia.clarkson@example.com",
      "quincy.lopez@example.com",
      "rachel.walker@example.com",
    ],
  },
  {
    id: 7,
    date: {
      start: "2024-07-20T08:00:00.000Z",
      end: "2024-07-20T09:00:00.000Z",
    },
    location: "Office, Room 105",
    title: "Team Building Workshop",
    invites: [
      "samuel.thomas@example.com",
      "tina.anderson@example.com",
      "uma.lee@example.com",
    ],
  },
  {
    id: 8,
    date: {
      start: "2024-07-25T13:00:00.000Z",
      end: "2024-07-25T14:00:00.000Z",
    },
    location: "Online",
    title: "Quarterly Review",
    invites: [
      "victor.young@example.com",
      "wendy.ross@example.com",
      "xander.green@example.com",
    ],
  },
  {
    id: 9,
    date: {
      start: "2024-09-05T11:30:00.000Z",
      end: "2024-09-05T12:30:00.000Z",
    },
    location: "Conference Hall B",
    title: "Product Launch",
    invites: [
      "yara.white@example.com",
      "zachary.lee@example.com",
      "alexis.hughes@example.com",
    ],
  },
  {
    id: 10,
    date: {
      start: "2024-09-10T17:00:00.000Z",
      end: "2024-09-10T18:00:00.000Z",
    },
    location: "Online",
    title: "Customer Feedback Session",
    invites: [
      "beth.evans@example.com",
      "cameron.turner@example.com",
      "diana.harris@example.com",
      "ava.thomas@example.com",
      "joseph.harris@example.com",
    ],
  },
  {
    id: 11,
    date: {
      start: "2024-09-15T09:30:00.000Z",
      end: "2024-09-15T11:00:00.000Z",
    },
    location: "Office, Room 210",
    title: "Development Sprint Planning",
    invites: [
      "elijah.baker@example.com",
      "fiona.bell@example.com",
      "gabriel.morgan@example.com",
      "olivia.martin@example.com",
      "charles.walker@example.com",
      "ava.thomas@example.com",
      "joseph.harris@example.com",
      "maria.miller@example.com",
      "william.lee@example.com",
    ],
  },
  {
    id: 12,
    date: {
      start: "2024-09-20T14:00:00.000Z",
      end: "2024-09-20T15:30:00.000Z",
    },
    location: "Online",
    title: "Investor Meeting",
    invites: [
      "henry.adams@example.com",
      "isabella.reed@example.com",
      "jackson.carter@example.com",
      "emily.james@example.com",
      "michael.brown@example.com",
      "sarah.smith@example.com",
      "david.johnson@example.com",
      "laura.white@example.com",
      "james.lee@example.com",
      "olivia.martin@example.com",
      "charles.walker@example.com",
      "ava.thomas@example.com",
      "joseph.harris@example.com",
      "maria.miller@example.com",
      "william.lee@example.com",
      "sofia.rodriguez@example.com",
      "benjamin.moore@example.com",
      "ella.wood@example.com",
      "aiden.ross@example.com",
      "mia.jameson@example.com",
      "ryan.baker@example.com",
      "samantha.garcia@example.com",
      "elijah.morris@example.com",
      "lucas.hall@example.com",
      "ariana.jones@example.com",
      "noah.davis@example.com",
    ],
  },
  {
    id: 11,
    date: {
      start: "2024-08-02T22:30:00.000Z",
      end: "2024-08-02T23:30:00.000Z",
    },
    location: "Online",
    title: "Test",
    invites: [
      "george.clark@example.com",
      "hannah.martin@example.com",
      "ian.davis@example.com",
    ],
  },
];
